spring.application.name=currency-converter

currency_converter.base.url=https://api.freecurrencyapi.com/v1/latest?apikey=fca_live_7OBRfBN2QXWewQ77Q8rxsXqEAOOOKYnjVFZI9n4B
currency_converter.api.key=fca_live_7OBRfBN2QXWewQ77Q8rxsXqEAOOOKYnjVFZI9n4B